site_name: 'Python App'
site_description: 'Main documentation for Python App'
repo_url: https://github.com/Datasciencewebdevelopmentcoder/Python_app
edit_uri: edit/main/docs/

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        index.md: overview/what-is-backstage.md

nav:
  - Overview:
      - Getting Started: index.md
